### ISSUE TITLE
Upgrade pkg/analyzer to ^0.27.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/code_transformers#31]

**Comment by sigurdm** [comment]
cc @eernstg  - we should check out if that works well with reflectable.

**Comment by jakemac53** [comment]
cc @sigurdm @eernstg yes this will also block polymer from updating

**Comment by eernstg** [comment]
I've performed a number of experiments with reflectable this afternoon, but I keep getting failures: Evaluation of constant values returns null where we used to get the expected value (this is with analyzer 0.26.4, which is the version that pub selects when I let it take the newest one it wants; code_transformers 0.3.0+1 says '<0.27.0').

**Comment by jakemac53** [comment]
@eernstg can you try with the `0.3.1` branch?

**Comment by jakemac53** [comment]
actually you can just use the published `0.3.1` version now

**Comment by eernstg** [comment]
Did that. Still seeing nulls.

**Comment by eernstg** [comment]
Everything works in reflectable with code_transformers 0.2.11 and analyzer 0.26.1+14 (including the adjustments I've made in order to catch more null values coming out of const evaluation).

With 0.3.0+1 and analyzer 0.26.1+14 we get failures in many test cases, but they are not _our_ test cases:

  test_reflectable/test/packages/test/src/runner/browser/iframe_test
  test_reflectable/test/packages/test/src/runner/vm/isolate_test
  test_reflectable/test/packages/test/src/backend/live_test

It surprises me that the test framework executes test cases inside `packages`.

Also, `pub upgrade` does not terminate (at least not within a 250 second time frame) in the package coverage_reflectable.

With code_transformers 0.3.0+1 and analyzer 0.26.4 (which is the newest one allowed with code_transformers 0.3.0+1) we get errors in our own test cases (46 out of 58 test cases fail, generally because they have `final _data = {};` which typically means that we got null whenever we tried to evaluate some constant values).

With code_transformers 0.3.1 and analyzer 0.27.0 we get exactly the same set of test case failures, and they generally have `final _data = {};` (there are two exceptions with a non-empty `_data`, but they still die because an entry is missing from that map).

Does anyone (@bwilkerson?) known why we get null from constant evaluation (that is, `AnnotationElementImpl.evaluationResult` and, if we are feeling lucky, `ElementAnnotation.constantValue`) where we used to get (meaningful) non-null values?

**Comment by bwilkerson** [comment]
I don't know for sure, but there's a good chance that it's the same issue that source_gen is seeing. There is a bug that causes AnalysisContext.[get|compute]LibraryElement to sometimes return a library element in which constants have not been computed. I am working on a fix.

**Comment by eernstg** [comment]
OK, sounds great! ;-)

**Comment by jakemac53** [comment]
>
> It surprises me that the test framework executes test cases inside
> packages.


This should definitely *not* be happening. No idea what could cause that to
happen but its either an error with the package or your setup and probably
worth investigating.

On Fri, Dec 11, 2015 at 7:02 AM, Brian Wilkerson <notifications@github.com>
wrote:

> I don't know for sure, but there's a good chance that it's the same issue
> that source_gen is seeing. There is a bug that causes
> AnalysisContext.[get|compute]LibraryElement to sometimes return a library
> element in which constants have not been computed. I am working on a fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/code_transformers/issues/31#issuecomment-163957705>
> .
>



-- 
- Jake MacDonald

**Comment by eernstg** [comment]
Here's a way to reproduce this phenomenon:

Fetch the most recent commit from reflectable (45214a14b632be635208bd91e58a66538d95026e), then change 'reflectable/pubspec.yaml's version constraint on code_transformers to '^0.3.0' rather than '^0.2.0', then run `cd tool; ./bottest`. Fails on tests from 'packages' such as 'test_reflectable/build/test/packages/test/src/runner/browser/iframe_test.dart'.

**Comment by jakemac53** [comment]
@eernstg my previous comment assumed you were using `package:test`, with the bot framework its entirely possible that this is normal :)

**Comment by eernstg** [comment]
It has never occurred before we tried using code_transformers ^0.3.0, so that would be for rather small values of 'normal'. ;-)

**Comment by eernstg** [comment]
We are now avoiding the spurious test cases by explicitly excluding `packages` in the .status files.
