### ISSUE TITLE
Using alpha version of analyzer

### ISSUE THREAD

**Issue by jrote1** [dart-lang/code_transformers#41]
Should this be requiring a alpha build of analyzer for a release build. This is causing issues with dart style due to a issue with the alpha version of analyzer.

But either way I dont think release package should be using less than release package for something else

**Comment by jakemac53** [comment]
The release version should be out soon, and it is a breaking change for this package since it relies on some things directly from the `src` dir. Because of this I decided the easiest way to make sure there were not a period of breakage was to release a version which depends on the alpha release (the changes are not backwards compatible).
